name: 'Manjaro Package Action'
description: 'Builds Manjaro Packages'

inputs:
  package:
    description: 'PKGBUILD repo name'
    required: true
  source:
    description: 'custom package repo source'
    required: false
  branch:
    description: 'branch to build against'
    default: unstable
    required: false
  custom-repo:
    description: 'custom repo'
    required: false
  multilib:
    description: 'build multilib package'
    required: false
    default: false
  repo:
    description: 'package repo'
    required: true
  gpg-key:
    descriptio: 'gpg signing key'
    required: true
  gpg-passphrase:
    description: 'gpg passphrase'
    required: true

runs:
  using: "composite"
  steps:
    - name: install build-dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install \
        build-essential \
        cmake \
        fakeroot \
        git \
        libarchive-dev \
        libarchive-tools \
        libcurl4-openssl-dev \
        libgpgme-dev \
        libssl-dev \
        zip \
        python3-pip
        sudo pip3 install meson
        sudo pip3 install ninja
    - name: install pacman
      shell: bash
      env:
        PACMAN_VERSION: 6.0.1
      run: |
        sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/pacman.git
        pushd pacman
        sudo wget https://sources.archlinux.org/other/pacman/pacman-${PACMAN_VERSION}.tar.xz
        sudo tar -xvf pacman-${PACMAN_VERSION}.tar.xz
        pushd pacman-${PACMAN_VERSION}
        sudo patch -p1 -i ../pacman-sync-first-option.patch
        sudo meson --prefix=/usr \
                    --buildtype=plain \
                    -Ddoc=disabled \
                    -Ddoxygen=enabled \
                    -Dscriptlet-shell=/usr/bin/bash \
                    -Dldconfig=/usr/bin/ldconfig \
                    build
        sudo meson compile -C build
        sudo meson install -C build
        popd
        sudo install -m644 pacman.conf /etc/pacman.conf
        sudo install -m644 makepkg.conf /etc/
        sudo mkdir -p /etc/pacman.d
        sudo touch /etc/pacman.d/mirrorlist
        popd
        sudo rm -rf pacman
    - name: install keyrings
      shell: bash
      run: |
        sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/manjaro-keyring.git
        pushd manjaro-keyring
        sudo install -dm755 /usr/share/pacman/keyrings/
        sudo install -m0644 manjaro.gpg /usr/share/pacman/keyrings/
        sudo install -m0644 manjaro-trusted /usr/share/pacman/keyrings/
        sudo install -m0644 manjaro-trusted /usr/share/pacman/keyrings/
        popd
        sudo rm -rf manjaro-keyring
         
        sudo git clone --depth 1 https://gitlab.archlinux.org/archlinux/archlinux-keyring.git
        pushd archlinux-keyring
        sudo install -m0644 archlinux.gpg /usr/share/pacman/keyrings/
        sudo install -m0644 archlinux-trusted /usr/share/pacman/keyrings/
        sudo install -m0644 archlinux-revoked /usr/share/pacman/keyrings/
        popd
        sudo rm -rf arhclinux-keyring
        sudo pacman-key --init
        sudo pacman-key --populate archlinux manjaro
    - name: install manjaro-chrootbuild
      shell: bash
      run: |
        sudo git clone --depth 1 https://gitlab.manjaro.org/tools/development-tools/manjaro-chrootbuild
        pushd manjaro-chrootbuild
        sudo ./install.sh
        echo "PACKAGER = Manjaro Build Server <build@manjaro.org>" | sudo tee -a /etc/makepkg.conf > /dev/null
        popd
        sudo rm -rf manjaro-chrootbuild
    - name: clone package repo
      shell: bash
      run: |
        if [[ ! -z "${{ inputs.source }}" ]]; then
          source=${{ inputs.source }}
        else
          source=https://gitlab.manjaro.org/packages/${{ inputs.repo }}/${{ inputs.package }}.git
        fi
        sudo git clone ${source}
    - name: build package
      shell: bash
      run: |
        build_opt=("-p ${{ inputs.package }}" "-b ${{ inputs.branch }}")
        [[ ! -z "${{ inputs.custom-repo }}" ]] && build_opt+=("-k ${{ inputs.custom-repo }}")
        [[ "${{ inputs.multilib }}" == "true" ]] && build_opt+=("-m")
        echo "cmd=chrootbuild ${build_opt[@]}"
        sudo chrootbuild ${build_opt[@]}
    - name: sign package
      shell: bash -O extglob {0}
      run: |      
        cat <(echo -e "${{ inputs.gpg-key }}" | base64 --decode) | gpg --batch --import &>/dev/null
        for p in $(find $PWD -maxdepth 1 -regex '.*\.pkg\.tar\.\(xz\|zst\)'); do
          gpg --pinentry-mode loopback --passphrase "${{ inputs.gpg-passphrase }}" --detach-sign ${p}
        done
    - name: prepare assets transaction
      shell: bash -O extglob {0}
      run: |
        source /var/lib/chrootbuild/build/${{ inputs.package }}/PKGBUILD
        tag=${pkgver}-${pkgrel}
        for p in ${pkgname[@]}; do
          name=$(find . -name ${p}-${tag}*.zst)
          arch=$(echo ${name} | rev | cut -d- -f1 | rev | cut -d. -f1)
          file=${p}-${tag}-${arch}
          btf=${file}.yml # boxit transaction file
          echo "sha256_pkg: $(sha256sum ${p}*.zst | cut -d' ' -f1)" > ${btf}
          echo "sha256_sig: $(sha256sum ${p}*.sig | cut -d' ' -f1)" >> ${btf}
          [[ "${p}" == "mhwd-nvidia" ]] && _repo=core || _repo=${{ inputs.repo }}
          echo "repository: ${_repo}" >> ${btf}
          echo "branch: ${{ inputs.branch }}" >> ${btf}
          tar -czvf ${file}.tar ./${_file}*.zst ./${file}*.sig ./${btf}
        done
        echo "TAG=${tag}" >>$GITHUB_ENV
    - name: publish package
      shell: bash -O extglob {0}
      run: |
        release=${{ inputs.package }}-${{ env.TAG }}
        echo ${{ github.token }} | gh auth login --with-token
        gh release create ${release} --title ${release} --repo ${{ github.repository }} --notes "automated release" || echo "release already exists"
        GITHUB_LINK=https://github.com/${GITHUB_REPOSITORY}/releases/download/${release}
        gh release upload ${release} --repo ${GITHUB_REPOSITORY} --clobber ./*.zst ./*.sig ./*.tar
